// ALERT
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// LOG IN
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

// SIGN UP
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

// LOG OUT
export const LOGOUT = 'LOGOUT';

// LOAD USER
export const LOADUSER_REQUEST = 'LOADUSER_REQUEST';
export const LOADUSER_SUCCESS = 'LOADUSER_SUCCESS';
export const LOADUSER_ERROR = 'LOADUSER_ERROR';
