// ALERT =================================================

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// AUTH ==================================================

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const LOGOUT = 'LOGOUT';

export const LOADUSER_REQUEST = 'LOADUSER_REQUEST';
export const LOADUSER_SUCCESS = 'LOADUSER_SUCCESS';
export const LOADUSER_ERROR = 'LOADUSER_ERROR';

// SEARCH ================================================

export const SEARCHUSER_REQUEST = 'SEARCHUSER_REQUEST';
export const SEARCHUSER_SUCCESS = 'SEARCHUSER_SUCCESS';
export const SEARCHUSER_ERROR = 'SEARCHUSER_ERROR';
export const SEARCHUSER_CANCEL = 'SEARCHUSER_CANCEL';
export const SEARCHUSER_CLEAR = 'SEARCHUSER_CLEAR';

// USERS =================================================

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_ERROR = 'GET_USER_ERROR';

// POSTS =================================================

export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_ERROR = 'CREATE_POST_ERROR';

export const EDIT_POST_REQUEST = 'EDIT_POST_REQUEST';
export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS';
export const EDIT_POST_ERROR = 'EDIT_POST_ERROR';

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_ERROR = 'DELETE_POST_ERROR';

export const GET_POST_REQUEST = 'GET_POST_REQUEST';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POST_ERROR = 'GET_POST_ERROR';

export const GET_POSTS_REQUEST = 'GET_POSTS_REQUEST';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_ERROR = 'GET_POSTS_ERROR';

export const CREATE_COMMENT_REQUEST = 'CREATE_COMMENT_REQUEST';
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_ERROR = 'CREATE_COMMENT_ERROR';

export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_ERROR = 'DELETE_COMMENT_ERROR';

export const LIKE_POST_REQUEST = 'LIKE_POST_REQUEST';
export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS';
export const LIKE_POST_ERROR = 'LIKE_POST_ERROR';

export const CLEAR_POSTS = 'CLEAR_POSTS';

// MOMENTS ===============================================

export const GET_MOMENTS_REQUEST = 'GET_MOMENTS_REQUEST';
export const GET_MOMENTS_SUCCESS = 'GET_MOMENTS_SUCCESS';
export const GET_MOMENTS_ERROR = 'GET_MOMENTS_ERROR';

export const CREATE_MOMENT_REQUEST = 'CREATE_MOMENT_REQUEST';
export const CREATE_MOMENT_SUCCESS = 'CREATE_MOMENT_SUCCESS';
export const CREATE_MOMENT_ERROR = 'CREATE_MOMENT_ERROR';

export const DELETE_MOMENT_REQUEST = 'DELETE_MOMENT_REQUEST';
export const DELETE_MOMENT_SUCCESS = 'DELETE_MOMENT_SUCCESS';
export const DELETE_MOMENT_ERROR = 'DELETE_MOMENT_ERROR';

export const REACT_MOMENT_REQUEST = 'REACT_MOMENT_REQUEST';
export const REACT_MOMENT_SUCCESS = 'REACT_MOMENT_SUCCESS';
export const REACT_MOMENT_ERROR = 'REACT_MOMENT_ERROR';
